export const SET_COLLECTIBLE_DATA = "SET_COLLECTIBLE_DATA";
export const SET_COLLECTIBLE_METADATA = "SET_COLLECTIBLE_METADATA";
export const SET_ERROR = "SET_ERROR";
export const RESET_COLLECTIBLE = "RESET_COLLECTIBLE";
